version: '3.1'

services:
  api:
    build: .
    ports:
      - "8001:8000"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "${FSTR_PASS}"
      POSTGRES_USER: "${FSTR_LOGIN}"
      POSTGRES_DB: ${POSTGRES_DB}"
    ports:
      - "5432:5432"
